#!/usr/bin/env python3
"""Build a side-by-side comparison table from flow signal summary JSON files."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd


PROJECT_DIR = Path(__file__).resolve().parent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build comparison CSV/HTML from multiple *_flow_signals_*_summary.json files."
    )
    parser.add_argument(
        "--summaries",
        nargs="+",
        type=Path,
        required=True,
        help="Summary JSON files generated by build_flow_signal_pack.py.",
    )
    parser.add_argument(
        "--output-prefix",
        default="flow_signals_comparison",
        help="Output filename prefix (without extension).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_DIR,
        help="Output directory.",
    )
    return parser.parse_args()


def classify_score(score: float) -> str:
    if score > 0.3:
        return "bullish_strong"
    if score > 0.1:
        return "bullish_moderate"
    if score >= -0.1:
        return "neutral"
    if score >= -0.3:
        return "bearish_moderate"
    return "bearish_strong"


def load_summary(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Summary not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    required = ["symbol", "session_date", "composite_score"]
    missing = [key for key in required if key not in data]
    if missing:
        raise ValueError(f"{path.name} missing keys: {missing}")
    return data


def generate_html(df: pd.DataFrame, output_path: Path) -> None:
    html_df = df.copy()
    for column in ["smfi", "dex_norm", "pc_ratio", "fms_last", "composite_score"]:
        html_df[column] = html_df[column].map(lambda x: f"{x:.3f}")
    html_df["premium_total"] = html_df["premium_total"].map(lambda x: f"${x:,.0f}")
    html_df["gex_total"] = html_df["gex_total"].map(lambda x: f"{x:,.0f}")
    html_df["pin_strike"] = html_df["pin_strike"].map(lambda x: f"{x:.2f}" if pd.notna(x) else "N/A")

    table_html = html_df.to_html(index=False, border=0, classes="comparison")
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Flow Signals Comparison</title>
  <style>
    body {{
      margin: 0;
      font-family: "Space Grotesk", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #0b1220;
      color: #e6edf8;
      padding: 20px;
    }}
    .wrap {{
      max-width: 1100px;
      margin: 0 auto;
      border: 1px solid #22314f;
      border-radius: 12px;
      background: #111b2f;
      padding: 14px;
    }}
    h1 {{
      margin: 0 0 12px;
      font-size: 24px;
    }}
    table.comparison {{
      width: 100%;
      border-collapse: collapse;
      font-size: 13px;
    }}
    table.comparison th, table.comparison td {{
      border-bottom: 1px solid #22314f;
      text-align: left;
      padding: 8px;
      white-space: nowrap;
    }}
    table.comparison th {{
      color: #9fb2d3;
      text-transform: uppercase;
      font-size: 11px;
    }}
    .muted {{
      color: #9fb2d3;
      font-size: 12px;
      margin-bottom: 10px;
    }}
    @media (max-width: 860px) {{
      .wrap {{ overflow-x: auto; }}
    }}
  </style>
</head>
<body>
  <div class="wrap">
    <h1>Flow Signals Comparison</h1>
    <div class="muted">Ranked by composite_score (highest to lowest)</div>
    {table_html}
  </div>
</body>
</html>
"""
    output_path.write_text(html, encoding="utf-8")


def main() -> int:
    args = parse_args()
    summaries = [load_summary(path.expanduser().resolve()) for path in args.summaries]

    rows = []
    for item in summaries:
        score = float(item.get("composite_score", 0.0))
        rows.append(
            {
                "symbol": item.get("symbol"),
                "session_date": item.get("session_date"),
                "composite_score": score,
                "label": item.get("composite_label") or classify_score(score),
                "smfi": float(item.get("smfi", 0.0)),
                "dex_norm": float(item.get("dex_norm", 0.0)),
                "pc_ratio": float(item.get("pc_ratio", 0.0)),
                "fms_last": float(item.get("fms_last", 0.0)),
                "premium_total": float(item.get("premium_total", 0.0)),
                "gex_total": float(item.get("gex_total", 0.0)),
                "pin_strike": item.get("pin_strike"),
                "gex_regime": item.get("gex_regime"),
                "total_trades": int(item.get("total_trades", 0)),
            }
        )

    df = pd.DataFrame(rows).sort_values("composite_score", ascending=False).reset_index(drop=True)

    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    csv_path = output_dir / f"{args.output_prefix}.csv"
    html_path = output_dir / f"{args.output_prefix}.html"

    df.to_csv(csv_path, index=False)
    generate_html(df, html_path)

    print(
        json.dumps(
            {
                "rows": len(df),
                "outputs": {"csv": str(csv_path), "html": str(html_path)},
                "ranking": df[["symbol", "composite_score", "label"]].to_dict(orient="records"),
            },
            indent=2,
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
